apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-streaming-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-streaming
  template:
    metadata:
      labels:
        app: nats-streaming
    spec:
      containers:
        - name: nats-streaming-container
          image: nats-streaming:0.17.0
          args: [
            '-p',
            '4222',
            '-m',
            '8222',
            '-hbi', ##check time status(es el chequeo d elatido que ayuda a identifical la salud de los eventos y su recepcion fallida o no cuando un cliente(listen) se desconecta)
            '5s',
            '-hbt',
            '5s',
            '-hbf', ##numero de veces que puede fallar para que nats asuma que la conexion esta muerta
            '2',
            '-SD',
            '-cid', ##asigna el id del cluster ticketing
            'ticketing' ##nombre que se usa para configurara el cliente del nats desde el backend que lo consuma
          ]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-streaming-services ##nombre que tendra el servicio que comunica los pods dentro del cluster y de la configuracion del cliente nats del backend
spec:
  selector:
    app: nats-streaming
  type: ClusterIP 
  ports:  
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222